name: cloudburst

services:
    postgresql:
        image: bitnami/postgresql:latest
        restart: unless-stopped
        ports:
            - "2345:5432/tcp"
        volumes:
            - cloudburst-data:/bitnami/postgresql
        environment:
            - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_user
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=manpost
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

    redis:
        image: bitnami/redis:latest
        restart: unless-stopped
        volumes:
            - redis-data:/data
        ports:
            - "6380:6379/tcp"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

    registry:
        image: registry:latest
        ports:
            - "5678:5000"
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
            - registry:/data
        restart: unless-stopped

    backend:
        image: ghcr.io/manangandhi1810/manpost-backend:latest
        restart: unless-stopped
        ports:
            - "2222:8000/tcp"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./backend/.env.prod
        command: sh -c "pnpx prisma migrate deploy && pnpm run start"

volumes:
    cloudburst-data:
    registry:
    redis-data:
